
[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20"
PLAYWRIGHT_BROWSERS_PATH = "0"

[[redirects]]
from = "/2024/canvas-plum/*"
to = "/2024/canvas-plum/index.html"
status = 200

[[redirects]]
from = "/2025/fed-day-fuzhou/*"
to = "/2025/fed-day-fuzhou/index.html"
status = 200

[[redirects]]
from = "/2025/cib-ai-conf/*"
to = "/2025/cib-ai-conf/index.html"
status = 200
