
[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20"
PLAYWRIGHT_BROWSERS_PATH = "0"

[[redirects]]
from = "/2024/canvas-plum/*"
to = "/2024/canvas-plum/index.html"
status = 200
